import { VanillaExtractPlugin } from "@vanilla-extract/webpack-plugin";
import { defineConfig } from "cypress";
import MiniCssExtractPlugin from "mini-css-extract-plugin";

// eslint-disable-next-line import/no-default-export
export default defineConfig({
	component: {
		devServer: {
			bundler: "webpack",
			framework: "react",
			webpackConfig: async () => {
				return {
					devtool: "eval-source-map",
					mode: "development",
					module: {
						rules: [
							{
								exclude: [/node_modules/],
								test: /\.(ts|tsx)$/,
								use: [
									{
										loader: "ts-loader",
										options: {
											transpileOnly: true,
										},
									},
								],
							},
							{
								test: /\.vanilla\.css$/i, // Targets only CSS files generated by vanilla-extract
								use: [
									MiniCssExtractPlugin.loader,
									{
										loader: require.resolve("css-loader"),
										options: {
											url: false, // Required as image imports should be handled via JS/TS import statements
										},
									},
								],
							},
						],
					},
					plugins: [
						new VanillaExtractPlugin({
							identifiers: "short",
							outputCss: true,
						}),
						new MiniCssExtractPlugin(),
					],
					resolve: {
						extensions: [".ts", ".tsx", ".js", ".jsx"],
					},
				};
			},
		},
		specPattern: "**/*/spec.(ts|tsx)",
	},

	// e2e: {
	//     setupNodeEvents(on, config) {
	//         // implement node event listeners here
	//     },
	// },
});
