name: Auto patch version

on:
    push:
        branches:
            - main
        paths:
            - 'src/**'

permissions:
    contents: write
    pull-requests: write

jobs:
    test:
      uses: ./.github/workflows/test.yml
      secrets: 
        FONTAWESOME_TOKEN: ${{ secrets.FONTAWESOME_TOKEN }}
        
    auto-patch-version:
        runs-on: ubuntu-latest
        needs: test
        permissions:
            contents: write
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Patch NPM package version
              run: |
                git config user.name github-actions
                git config user.email github-actions@github.com
                git checkout -b update-package-json-${{ github.run_id }}
                npm version patch
                git push --tags --no-verify
                gh pr create --title "chore: update package.json version" --body "This PR updates the package.json version after changes in the src directory." --base main --head update-package-json-${{ github.run_id }}
              env:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
