name: Auto-tag

on:
    push:
        branches:
            - main
        paths:
            - 'src/**'

permissions:
    id-token: write
    deployments: write
    contents: write

jobs:
    code-quality:
      name: Code quality
      uses: ./.github/workflows/code-quality.yml
      secrets: 
        FONTAWESOME_TOKEN: ${{ secrets.FONTAWESOME_TOKEN }}
        
    auto-tag:
        name: Auto-tag
        runs-on: ubuntu-latest
        needs: code-quality
        permissions:
            contents: write
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Patch NPM package version
              run: |
                git config user.name github-actions
                git config user.email github-actions@github.com
                git checkout -b update-package-json-${{ github.run_id }}
                npm version patch
                git push --tags --no-verify
                gh pr create --title "chore: update package.json version" --body "This PR updates the package.json version after changes in the src directory." --base main --head update-package-json-${{ github.run_id }}
              env:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
