name: check

on:
  workflow_dispatch:

  push:
    branches:
      - master

jobs:
  install_and_check:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    name: Check
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # 👈 Required to retrieve git history
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: "npm"
          # cache-dependency-path: subdir/package-lock.json
      - run: npm ci
      - run: npm run check
      - name: Chromatic
        uses: chromaui/action@v1
        with:
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
