name: TrustyPkg Dependency Check

on:
    pull_request:
        branches:
            - main

permissions:
    pull-requests: write

jobs:
    trusty_pkg_check:
        runs-on: ubuntu-latest
        name: Check Dependencies with TrustyPkg
        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: TrustyPkg Action
              uses: stacklok/trusty-action@v0.0.6
              with:
                  global_threshold: 5
                  provenance_threshold: 5
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
